### ISSUE TITLE
does not work with PHP 7, txp 4.6.2

### ISSUE THREAD

**Issue by johnnybubonic** [drmonkeyninja/TXP-Tweet#21]
when i try 4.3.2 of the plugin or the current HEAD, it refuses to even install. either it doesn't fit in the plugin paste box (requiring a compressed version), but even with the compressed version it still refuses to install, giving the "Badly formed or empty plugin code." error.

**Comment by drmonkeyninja** [comment]
hi @johnnybubonic thanks for reporting this issue. I haven't had chance to update the plugin to work with the latest version of Textpattern yet, mostly due to a lack of time. Issue #20 also needs addressing for the plugin to fully work with the new version of the CMS. I'm not quite sure what is causing your bug, but it might be related to how it is getting compressed. I will investigate.

**Comment by drmonkeyninja** [comment]
I've been unable to recreate this so closing the issue. If it re-occurs feel free to reopen it with further details.
